### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by alex3stones** [AmitMY/x-ng-table#1]
Hello, AmitMY

this is very nice job, and I will try on it :dancer:

**Comment by AmitMY** [comment]
I'm glad you liked it.

Unfortunately, I cannot with a clean heart recommend it over ag-grid.
after-grid handles most of the edge cases where this one fails, takes less code (sometimes) and does not render the full table all the time.

It is faster, with more options, and without stupid edge case bugs (example is if you send null some places here, it will through an error and not a warning)

Especially if you can afford ag-grid-enterprise which is so good. Just look at the demo they have in their main website, which take 2 hours to learn how to create, but works fenominaly.

I stopped working with it until my company buys it.

**Comment by alex3stones** [comment]
Thanks soooo much for your share. I am watching the demo and it looks pretty cool, and I will dig it for my project since its free release is totally good enough for me. Thanks again buddy!
